[package]
name = "panel"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
tokio = { version = "1.43.0", features = [
    "rt-multi-thread",
    "macros",
    "process",
    "fs",
] }
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
getrandom = "0.3.1"

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }

[profile.release]
strip = true
lto = true
opt-level = "z"
